/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeServicesRouteImport } from './routes/_home/services'
import { Route as HomeNetworkRouteImport } from './routes/_home/network'
import { Route as HomeIndustriesRouteImport } from './routes/_home/industries'
import { Route as HomeContactRouteImport } from './routes/_home/contact'
import { Route as HomeCareersRouteImport } from './routes/_home/careers'
import { Route as HomeAboutRouteImport } from './routes/_home/about'
import { Route as AuthUnauthorizedRouteImport } from './routes/_auth/unauthorized'
import { Route as AuthOperationsRouteImport } from './routes/_auth/operations'
import { Route as HomeServiceServiceIdRouteImport } from './routes/_home/service.$serviceId'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeNetworkRoute = HomeNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeIndustriesRoute = HomeIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeContactRoute = HomeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCareersRoute = HomeCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthUnauthorizedRoute = AuthUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOperationsRoute = AuthOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthRouteRoute,
} as any)
const HomeServiceServiceIdRoute = HomeServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/operations': typeof AuthOperationsRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/about': typeof HomeAboutRoute
  '/careers': typeof HomeCareersRoute
  '/contact': typeof HomeContactRoute
  '/industries': typeof HomeIndustriesRoute
  '/network': typeof HomeNetworkRoute
  '/services': typeof HomeServicesRoute
  '/service/$serviceId': typeof HomeServiceServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/operations': typeof AuthOperationsRoute
  '/unauthorized': typeof AuthUnauthorizedRoute
  '/about': typeof HomeAboutRoute
  '/careers': typeof HomeCareersRoute
  '/contact': typeof HomeContactRoute
  '/industries': typeof HomeIndustriesRoute
  '/network': typeof HomeNetworkRoute
  '/services': typeof HomeServicesRoute
  '/service/$serviceId': typeof HomeServiceServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_home': typeof HomeRouteRouteWithChildren
  '/_auth/operations': typeof AuthOperationsRoute
  '/_auth/unauthorized': typeof AuthUnauthorizedRoute
  '/_home/about': typeof HomeAboutRoute
  '/_home/careers': typeof HomeCareersRoute
  '/_home/contact': typeof HomeContactRoute
  '/_home/industries': typeof HomeIndustriesRoute
  '/_home/network': typeof HomeNetworkRoute
  '/_home/services': typeof HomeServicesRoute
  '/_home/': typeof HomeIndexRoute
  '/_home/service/$serviceId': typeof HomeServiceServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/operations'
    | '/unauthorized'
    | '/about'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/network'
    | '/services'
    | '/service/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/operations'
    | '/unauthorized'
    | '/about'
    | '/careers'
    | '/contact'
    | '/industries'
    | '/network'
    | '/services'
    | '/service/$serviceId'
  id:
    | '__root__'
    | '/_auth'
    | '/_home'
    | '/_auth/operations'
    | '/_auth/unauthorized'
    | '/_home/about'
    | '/_home/careers'
    | '/_home/contact'
    | '/_home/industries'
    | '/_home/network'
    | '/_home/services'
    | '/_home/'
    | '/_home/service/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/services': {
      id: '/_home/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/network': {
      id: '/_home/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof HomeNetworkRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/industries': {
      id: '/_home/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof HomeIndustriesRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/contact': {
      id: '/_home/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof HomeContactRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/careers': {
      id: '/_home/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof HomeCareersRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_auth/unauthorized': {
      id: '/_auth/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthUnauthorizedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/operations': {
      id: '/_auth/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthOperationsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_home/service/$serviceId': {
      id: '/_home/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof HomeServiceServiceIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthOperationsRoute: typeof AuthOperationsRoute
  AuthUnauthorizedRoute: typeof AuthUnauthorizedRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthOperationsRoute: AuthOperationsRoute,
  AuthUnauthorizedRoute: AuthUnauthorizedRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface HomeRouteRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeCareersRoute: typeof HomeCareersRoute
  HomeContactRoute: typeof HomeContactRoute
  HomeIndustriesRoute: typeof HomeIndustriesRoute
  HomeNetworkRoute: typeof HomeNetworkRoute
  HomeServicesRoute: typeof HomeServicesRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeServiceServiceIdRoute: typeof HomeServiceServiceIdRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeCareersRoute: HomeCareersRoute,
  HomeContactRoute: HomeContactRoute,
  HomeIndustriesRoute: HomeIndustriesRoute,
  HomeNetworkRoute: HomeNetworkRoute,
  HomeServicesRoute: HomeServicesRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeServiceServiceIdRoute: HomeServiceServiceIdRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
